services:
  mysql:
    image: mysql:8.0
    container_name: api-gf-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345  
      MYSQL_DATABASE: Facturas    
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  db_data:
